namespace CardManager.Models.Cards.PokemonCards;

public enum PokemonRarity
{
    Unspecified,
    Common,
    Uncommon,
    Rare,
    DoubleRare,
    RareLvX,
    RareEx,
    RareGx,
    SecretRare,
    UltraRare,
    BreakRare,
    IllustartionRare,
    PrimeRare,
    SpecialIllustrationRare,
    RainbowRare,
    RadiantRare,
    FullArtRare,
    UltraRareStar,
    UltraRareEx1,
    UltraRareEx2,
    UltraRareLvX,
    UltraRareGx,
    UltraRareV,
    UltraRareVMax,
    UltraRareVStar,
    UltraRarePrime,
    UltraRareLegend,
    PromoRare,
    GoldHyperRare,
    TagTeamRare,
    AceRare,
}
